apiVersion: v1
kind: Service
metadata:
  name: my-cicd-service
spec:
  type: NodePort
  selector:
    app: my-cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036
