apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cicd-app
  template:
    metadata:
      labels:
        app: my-cicd-app
    spec:
      containers:
      - name: my-cicd-container
        docker build -t my-cicd-app:latest .
        ports:
        - containerPort: 5000
